/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1053054_9_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1053054_1[] = { "Anomaly", "Normal" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1053054_8_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127 };
const uint32_t ei_dsp_config_1053054_8_axes_size = 128;
ei_dsp_config_raw_t ei_dsp_config_1053054_8 = {
    8, // uint32_t blockId
    1, // int implementationVersion
    128, // int length of axes
    0.000001f // float scale-axes
};

const uint8_t ei_dsp_blocks_1053054_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1053054_1[ei_dsp_blocks_1053054_1_size] = {
    { // DSP block 8
        8,
        128, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_1053054_8, // pointer to config struct
        ei_dsp_config_1053054_8_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1053054_8_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        nullptr, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1053054_9 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1053054_9_init,
    .model_invoke = &tflite_learn_1053054_9_invoke,
    .model_reset = &tflite_learn_1053054_9_reset,
    .model_input = &tflite_learn_1053054_9_input,
    .model_output = &tflite_learn_1053054_9_output,
};

const uint8_t ei_output_tensors_indices_1053054_9[1] = { 0 };
const uint8_t ei_output_tensors_size_1053054_9 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1053054_9 = {
    .implementation_version = 1,
    .block_id = 9,
    .output_tensors_indices = ei_output_tensors_indices_1053054_9,
    .output_tensors_size = ei_output_tensors_size_1053054_9,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1053054_9,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1053054_1_size = 1;
const uint32_t ei_learning_block_1053054_9_inputs[1] = { 8 };
const uint8_t ei_learning_block_1053054_9_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1053054_1[ei_learning_blocks_1053054_1_size] = {
    {
        9,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1053054_9,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1053054_9_inputs,
        ei_learning_block_1053054_9_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1053054_9 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1053054_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1053054_1[ei_postprocessing_blocks_1053054_1_size] = {
    {
        .block_id = 9,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1053054_9,
        .input_block_id = 9
    },
};

const uint8_t freeform_outputs_1053054_1_size = 0;

uint32_t *freeform_outputs_1053054_1 = nullptr;

const ei_impulse_t impulse_1053054_1 = {
    .project_id = 1053054,
    .project_owner = "eitanmarock",
    .project_name = "eitanmarock-project-1",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 128,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 128,
    .dsp_input_frame_size = 1 * 128,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 2562,
    .frequency = 0.39032006245121,

    .dsp_blocks_size = ei_dsp_blocks_1053054_1_size,
    .dsp_blocks = ei_dsp_blocks_1053054_1,

    .learning_blocks_size = ei_learning_blocks_1053054_1_size,
    .learning_blocks = ei_learning_blocks_1053054_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1053054_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1053054_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "Freq_Bin_0 + Freq_Bin_1 + Freq_Bin_2 + Freq_Bin_3 + Freq_Bin_4 + Freq_Bin_5 + Freq_Bin_6 + Freq_Bin_7 + Freq_Bin_8 + Freq_Bin_9 + Freq_Bin_10 + Freq_Bin_11 + Freq_Bin_12 + Freq_Bin_13 + Freq_Bin_14 + Freq_Bin_15 + Freq_Bin_16 + Freq_Bin_17 + Freq_Bin_18 + Freq_Bin_19 + Freq_Bin_20 + Freq_Bin_21 + Freq_Bin_22 + Freq_Bin_23 + Freq_Bin_24 + Freq_Bin_25 + Freq_Bin_26 + Freq_Bin_27 + Freq_Bin_28 + Freq_Bin_29 + Freq_Bin_30 + Freq_Bin_31 + Freq_Bin_32 + Freq_Bin_33 + Freq_Bin_34 + Freq_Bin_35 + Freq_Bin_36 + Freq_Bin_37 + Freq_Bin_38 + Freq_Bin_39 + Freq_Bin_40 + Freq_Bin_41 + Freq_Bin_42 + Freq_Bin_43 + Freq_Bin_44 + Freq_Bin_45 + Freq_Bin_46 + Freq_Bin_47 + Freq_Bin_48 + Freq_Bin_49 + Freq_Bin_50 + Freq_Bin_51 + Freq_Bin_52 + Freq_Bin_53 + Freq_Bin_54 + Freq_Bin_55 + Freq_Bin_56 + Freq_Bin_57 + Freq_Bin_58 + Freq_Bin_59 + Freq_Bin_60 + Freq_Bin_61 + Freq_Bin_62 + Freq_Bin_63 + Freq_Bin_64 + Freq_Bin_65 + Freq_Bin_66 + Freq_Bin_67 + Freq_Bin_68 + Freq_Bin_69 + Freq_Bin_70 + Freq_Bin_71 + Freq_Bin_72 + Freq_Bin_73 + Freq_Bin_74 + Freq_Bin_75 + Freq_Bin_76 + Freq_Bin_77 + Freq_Bin_78 + Freq_Bin_79 + Freq_Bin_80 + Freq_Bin_81 + Freq_Bin_82 + Freq_Bin_83 + Freq_Bin_84 + Freq_Bin_85 + Freq_Bin_86 + Freq_Bin_87 + Freq_Bin_88 + Freq_Bin_89 + Freq_Bin_90 + Freq_Bin_91 + Freq_Bin_92 + Freq_Bin_93 + Freq_Bin_94 + Freq_Bin_95 + Freq_Bin_96 + Freq_Bin_97 + Freq_Bin_98 + Freq_Bin_99 + Freq_Bin_100 + Freq_Bin_101 + Freq_Bin_102 + Freq_Bin_103 + Freq_Bin_104 + Freq_Bin_105 + Freq_Bin_106 + Freq_Bin_107 + Freq_Bin_108 + Freq_Bin_109 + Freq_Bin_110 + Freq_Bin_111 + Freq_Bin_112 + Freq_Bin_113 + Freq_Bin_114 + Freq_Bin_115 + Freq_Bin_116 + Freq_Bin_117 + Freq_Bin_118 + Freq_Bin_119 + Freq_Bin_120 + Freq_Bin_121 + Freq_Bin_122 + Freq_Bin_123 + Freq_Bin_124 + Freq_Bin_125 + Freq_Bin_126 + Freq_Bin_127",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 2,
    .categories = ei_classifier_inferencing_categories_1053054_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1053054_1_size,
    .freeform_outputs = freeform_outputs_1053054_1
};

ei_impulse_handle_t impulse_handle_1053054_1 = ei_impulse_handle_t( &impulse_1053054_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1053054_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1053054_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1053054_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1053054_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
