/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 11.07.2026 13:55:14

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1488;
#else
constexpr int kTensorArenaSize = 464;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,128 } };
const TfArray<1, float> quant0_scale = { 1, { 0.022060735151171684, } };
const TfArray<1, int> quant0_zero = { 1, { -117 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[2] = { 309, -309, };
const TfArray<1, int> tensor_dimension1 = { 1, { 2 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00010743051825556904, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[2*10] = { 
  60, -105, 62, 107, 127, -77, -31, -108, 16, 93, 
  74, 23, -16, -28, -101, 2, -121, 60, -96, 25, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 2,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0059391474351286888, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -1123, -392, -41, 1192, 1441, -1077, 1385, -953, 1188, 1314, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 3.5987981391372159e-05, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  33, -64, -53, 23, 100, 15, 120, -104, 8, -53, 23, 19, 76, 127, 53, -69, 14, -31, -66, 30, 
  -53, -99, 83, 82, 51, -35, -45, -90, -79, 25, -42, -52, 78, 38, 77, 99, -32, 32, -37, -14, 
  -26, -104, -10, 96, -52, -58, -46, 16, -47, -18, 28, 40, -32, -87, -16, -77, 72, -99, -106, -85, 
  59, 6, 80, -6, -67, 88, -65, -50, -35, 68, 100, 57, -85, -90, 5, -41, -41, -38, 98, 88, 
  -31, 51, -95, -53, -77, 83, -40, 23, -85, 57, 86, 70, -32, 39, 35, -85, -60, 112, 65, 59, 
  -80, 83, -69, 62, -21, -125, 5, 82, -118, -39, 78, 51, -35, 67, -19, -71, -22, 50, -60, -4, 
  98, 39, -69, -89, 82, 93, 3, -38, -21, -2, 61, 53, -83, -44, 19, -9, 46, -4, -22, -22, 
  -19, 102, 61, 76, -9, 76, 99, -103, 122, -23, -52, 103, 81, -12, -98, 58, 101, -5, 21, 94, 
  69, 29, 39, 26, 89, 43, -112, -30, -38, 8, 88, 32, -19, -117, -32, 87, -101, 81, -52, -33, 
  53, -81, -31, -17, 80, 111, -24, 5, 68, -95, -58, 59, -89, -65, 58, -18, -34, 100, -4, 73, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0038892151787877083, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 1052, 554, -907, 443, -108, 1359, -857, -675, -680, 132, 836, 1455, 361, -523, 1188, -1065, 382, 1136, -699, 1419, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 4.3867461499758065e-05, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*128] = { 
  0, 7, -7, 93, 49, 59, 36, -54, 43, -74, 8, 38, -87, -61, -28, 79, 12, 62, -53, -44, 87, -25, 84, 19, -93, 62, -53, -55, -83, -99, 15, 23, 46, -90, -99, 43, -60, 85, 6, -38, 69, 18, -47, -9, -60, 105, -8, 117, -36, -44, 12, -63, 65, 14, -50, 92, 122, 101, 124, 82, 62, -26, 29, -57, -17, -58, 9, 38, 77, -13, 23, -87, -70, -33, -31, -65, 53, 36, -21, 76, 13, -13, -25, 24, -26, 4, -106, -18, -81, -92, 28, -27, -56, 77, -20, -104, 80, 46, -77, -28, 12, -90, 26, 45, -19, -29, -26, 10, -49, -41, 84, 23, -6, 59, -55, 88, -47, 41, -85, 37, 46, 7, 23, 93, -108, -23, 55, 2, 
  -98, -8, 88, 28, -25, 22, 44, 34, 57, 104, -56, 49, 25, 25, 69, -38, 97, 62, 113, -53, -8, 2, 90, -10, 60, 59, -13, 86, -2, -66, 2, 110, 96, 99, 72, -20, -75, -9, 20, -54, -49, -58, 90, 66, 52, -34, 72, -65, 3, 3, -86, -3, 13, -29, -11, -92, -83, 90, 89, -70, -9, 84, -37, -10, -15, 13, 85, -87, 63, -19, 86, -54, 54, 1, 17, 100, -10, -37, 6, 100, 6, -80, -35, 16, 56, 6, -6, -53, 33, -4, 36, 32, 95, 26, 14, 53, -44, -84, 6, -101, 8, 81, -14, -27, -74, 45, 73, -63, -21, -15, -28, -80, 110, 39, -17, 90, 30, 25, -72, -61, 36, -90, -20, -42, 65, 7, 13, 54, 
  65, 7, -65, -51, 63, -38, 74, 99, 88, -9, -74, 34, -53, 75, -37, 90, 50, 77, 18, 55, 117, -86, 63, -64, 19, -15, 107, 60, -41, -64, -33, 80, 68, -61, -7, -29, -74, 3, 69, -71, 44, 39, -89, -19, 29, -26, -62, -94, 18, -38, 40, -36, -32, -19, 37, -93, 1, 4, 4, -31, 94, -41, -11, 23, -12, 64, 29, -50, -16, -24, 17, -75, 34, 109, 11, -64, -61, 71, -28, -54, 48, -38, 51, 9, 31, 43, 2, 24, -52, 28, -45, 104, 44, -15, 121, 85, 48, 62, 57, 57, -66, -60, -24, -43, 67, -21, 91, 81, 28, -1, -28, 71, 24, -67, -55, -70, 57, 108, -17, 41, -39, 77, 103, -97, 78, 72, 11, 60, 
  -83, 76, -29, 83, 14, 82, 14, 120, 71, -60, 105, 106, 72, 86, 66, 1, -52, -25, 54, 82, -44, 61, -42, -14, 82, 73, -48, 82, 106, 88, -20, 64, 111, -23, 82, 32, 119, -77, 37, 76, -73, 75, 21, 95, 114, -61, 12, -57, 69, 53, -69, -18, -35, -106, 14, -61, -67, -82, -23, 7, 112, 49, 117, 94, -42, -67, 81, -63, -39, -67, 83, -26, -32, -46, 42, 58, -3, 123, 59, 111, 42, 84, 90, -12, 5, -54, 14, -17, 83, -16, 63, 55, -60, 36, 106, -15, -34, 5, 102, 1, -7, 15, 104, -33, -22, 19, 37, -2, 42, 52, -59, 40, 20, 95, 28, 112, -68, 24, 90, 14, -70, 101, 25, 52, -65, 22, 15, -43, 
  81, 26, 26, -53, -80, -73, 89, -22, -48, 52, -27, 18, -65, -39, -71, 52, 54, 61, -6, -28, -17, 86, -22, -16, -35, 0, 68, 63, -97, -83, 42, -70, 84, -73, -30, -55, -36, -96, 16, 53, 5, 22, -95, -42, 50, -69, 71, 55, -23, 63, 58, 66, -84, -24, -33, 95, 58, 71, 84, 53, -89, -86, 87, 89, 3, 54, -45, 94, -98, -27, -89, 22, 64, 30, 39, 42, -36, -31, -53, -43, 72, -92, 53, -70, 44, -54, 32, -64, 76, -41, -40, -3, 18, 60, 22, 1, 15, -25, -78, -77, -28, -92, 21, -37, 87, -56, -99, -25, -69, 26, -72, -7, -64, -9, 33, -14, -41, -71, -53, -17, 86, -32, -62, -14, -89, 1, 91, -84, 
  -30, 98, 37, 13, -11, -58, 33, 121, -13, 48, -69, -16, -77, 66, 37, 23, -69, 51, -7, 36, -54, -60, 11, -29, 96, -6, 39, -2, -37, 109, -5, 12, 84, -39, 45, -67, 93, -33, 66, 117, 95, 63, -56, -3, 41, -74, -50, -41, 22, 88, 112, 11, 58, -13, 68, 84, 58, 13, 81, 33, 51, -69, 89, -54, -5, 23, -15, 103, 102, 70, 91, -30, 55, -60, -93, -51, -24, -10, 57, 26, -52, 60, -27, 109, 15, -56, 21, 1, 103, -15, 8, 23, -52, 73, -4, -22, -18, 50, 2, 52, -21, 16, 67, -72, 11, 18, 113, -54, 47, 73, 2, 6, 42, 77, 89, 38, 68, -53, 54, -37, -81, 73, -54, 38, 19, 115, 8, -13, 
  49, -23, -22, -40, -53, -90, -24, 68, -44, -5, -18, -16, 3, 67, 52, -2, -24, -35, 114, 87, -34, 24, -34, 72, -34, -6, 102, -72, 94, 38, 81, -80, 10, -12, -72, 51, -93, 28, -92, 81, -30, 0, -28, -10, -67, -101, 80, -71, -28, -39, -84, 63, -103, 42, 17, -29, -8, 66, 39, -50, -78, -4, 57, -72, 42, 29, -79, 62, -57, -43, 33, 104, -13, 63, 45, 80, 65, 96, 61, -31, 90, 75, 18, 40, -39, -14, 79, 43, -29, -27, -54, 78, -22, 102, -28, -101, -64, -78, -105, -23, -64, -66, 0, -29, 103, -10, -22, -66, -52, 6, 3, 64, 76, -92, 34, -14, 48, -45, -88, -38, -46, 20, -73, 6, -25, -73, -1, 57, 
  74, -112, 15, 71, 75, 15, 15, 28, -46, 71, -32, 84, -50, 24, -82, -111, -49, -68, -84, 79, 69, -80, -69, -16, -37, 83, -40, 14, -109, -26, 9, 79, 6, -99, -48, -109, -34, 11, 54, -49, -34, 14, 86, 83, 20, -24, 8, -98, -69, 37, -80, -40, -29, 13, -43, -77, -101, 54, 52, -113, -81, -48, 37, -86, 39, 14, 11, -54, -58, 91, -70, 9, -27, 32, -11, 8, -47, 47, -64, 39, 85, -111, 48, -16, 15, -107, 30, 34, 57, -45, -37, -99, 1, -71, -97, -56, -50, -103, -10, 76, -47, 47, -17, -100, -26, -48, -58, -100, 79, -49, -72, -95, 1, 30, 69, -54, 62, -32, -52, 26, -47, 13, -25, -98, 25, 25, -80, -95, 
  55, 106, 70, -13, -88, 63, -13, -61, -13, -14, 17, 74, 62, -34, 27, -48, 47, -41, 104, 17, 86, 68, 86, 35, 61, 63, 79, -5, 90, -76, 65, -93, -6, 0, -79, -34, -88, 77, -76, -4, -61, -65, -105, -52, -103, 14, -50, -28, -69, 15, -108, -115, 79, -78, 37, 33, -1, 34, -25, -53, 51, -35, 73, -48, -2, -105, 76, 65, 58, -57, -32, -31, 25, -84, -33, -90, -64, -42, -60, 87, -42, -43, -64, -27, 104, 38, 11, 53, 77, 77, 23, -71, -73, -5, 93, 11, 104, 38, 58, -58, -84, -70, -45, 55, 18, 79, -17, 20, 25, -9, -51, 63, 12, 44, 82, 94, 34, -63, 79, -34, 61, 74, 1, -37, 48, -97, 11, 86, 
  -84, 42, -93, -10, -65, 50, -101, -13, -64, -105, -90, -72, -110, -34, -72, 68, -26, 46, 62, -67, -29, 62, 15, 87, 93, 60, -6, 17, -17, 33, -53, -37, -84, -7, 67, 27, 65, 75, -14, 25, 39, 47, -54, 27, -35, -93, 68, 55, 99, -69, 66, 115, -80, -83, -49, 16, 54, 15, -88, 26, -94, -56, -73, 70, -8, -32, -106, -33, -79, 32, -72, 57, 80, -8, -27, -88, 78, -40, -110, 68, 36, 89, -92, -62, -81, 68, -81, -62, 39, 16, 73, 30, -37, -22, 1, 81, -12, -101, -87, -54, 55, -80, -81, -41, 6, -12, -108, -51, 36, 30, 44, -64, -50, -50, 78, 57, 79, 56, 70, 48, 71, -100, -56, 79, -69, 35, 60, -41, 
  97, 13, 37, -103, -80, -49, 56, 15, 1, 40, -63, 30, 26, -83, 39, -64, -12, -10, 30, 22, -84, 44, -95, 75, 81, -18, -54, -35, 61, 68, -99, -83, -84, -18, 103, 100, -19, -67, -73, 49, 51, -12, 1, -30, -35, 72, 16, -83, 62, 55, -3, -28, 16, 23, 95, 113, -41, -21, 45, 3, 45, 58, 80, 81, 36, -90, -87, 54, 45, 32, 74, 7, -27, -46, -11, 75, 15, -70, 36, 100, -47, -74, 24, -73, -53, 54, -44, 18, -47, -58, -12, 82, 37, -58, -20, 4, -52, 41, -100, 30, 66, 44, 30, 24, 33, -59, -3, -100, 66, -1, -34, -7, 24, 44, -103, 5, -35, 87, -32, -60, -58, -94, -66, -83, 69, 39, -82, 12, 
  -14, 60, 114, -5, -51, -63, 126, -14, 102, 4, 111, 115, 87, 114, -13, 71, -18, -9, 118, 32, 5, 3, 120, 28, 55, 64, 84, 69, 121, 56, 13, 1, 21, -15, 52, 5, -43, 53, 53, 84, 73, 100, 106, 9, -28, -5, 49, 74, -60, 18, -49, 94, 57, 62, 118, 84, 77, 10, 38, -54, 103, 82, 23, -1, 96, 86, 90, 2, 2, 2, -62, 25, -54, -38, 96, 43, 52, 104, 62, 47, 69, 115, -58, -24, -66, -59, -49, 69, 9, 84, 69, -55, -74, -57, 35, 27, 48, 88, -4, -23, -9, -13, 65, 60, 58, 50, 33, 117, 20, -60, 0, 44, 64, 56, -66, -41, -67, 35, 90, 62, 123, 114, 33, 7, 18, 1, -26, -49, 
  -46, -74, 23, -10, 84, -64, -38, -76, -64, 68, -4, -70, 48, 77, -11, 96, 36, -11, 103, -9, 68, 75, -41, 85, 73, -8, 33, -21, 111, 3, -15, 47, -74, 108, 83, 80, 101, -49, -67, -57, -6, 29, -62, -29, -80, -21, 109, 71, -1, 115, 80, -85, -102, -3, -68, -88, -52, 44, -4, 61, -15, -58, -57, 88, 40, 47, 90, 60, 32, 89, 22, -25, 66, 86, 47, -73, -11, 101, -62, -75, 34, 60, 103, 81, 114, 97, -66, -33, 26, 83, -47, 111, 42, 41, -43, -61, 58, 30, 89, 6, -41, 82, 71, 57, 22, -60, 15, 104, 74, 37, 17, -11, 25, -28, -46, 38, -28, -14, 105, 70, 79, 10, 55, -34, 53, 59, -83, 73, 
  24, -83, -42, 13, 106, 118, -65, 116, 4, 48, 41, 51, 112, 49, 1, -49, -77, 5, -72, -29, -66, -68, 12, -12, -24, -80, -47, 110, 4, 25, 58, -80, -47, -83, -1, 33, 56, 3, 89, -37, 85, 50, 100, -62, 96, -43, -4, 50, 97, 50, 15, 24, -93, -67, 72, -51, 9, 70, 50, -16, 12, -39, 1, -60, 87, 89, 104, 92, 42, 114, -59, 0, 86, -1, 64, -52, -26, -25, 64, -66, -29, 54, -12, -17, 75, 36, 82, 101, 18, -69, 28, 48, -41, 85, -63, -40, -13, 121, 25, -28, 43, 110, 45, -51, -39, 64, 24, 11, -7, 64, 84, -68, -42, 48, -46, 72, 72, -48, 64, -79, 16, -23, -29, -20, 107, 33, -69, 89, 
  91, -80, -58, 17, 12, -52, -34, 50, 65, 45, 108, -100, -80, 103, -101, -42, -101, 12, 56, -66, 88, 100, -47, 84, -79, -47, -5, -75, 86, -27, 93, -57, -53, 61, -18, -54, -72, 40, 90, -74, -87, 93, -100, 74, 3, 81, -13, -37, -70, -14, 9, 72, 60, 16, -43, -35, 121, 7, 114, -29, 30, 69, -43, 110, 21, 100, 97, 72, -25, 57, -5, -69, 74, -51, 73, 31, -55, 14, -17, 7, 37, 1, -79, -49, 6, -89, 61, -2, -95, 9, -53, 30, -19, 50, -93, -14, 67, 80, 71, 88, -97, 83, -72, 64, -83, -25, 75, -88, -33, -51, -37, -2, 90, 56, -89, 64, 103, -74, 83, 87, -53, -14, -10, -54, -62, -71, 6, 105, 
  0, 91, -69, -92, -93, 25, -20, 11, 19, 22, -16, 45, -48, 59, 60, 82, 30, 47, 33, 47, -99, 76, -87, 36, 15, -3, -39, -29, -21, -50, 34, -40, -30, 46, -13, 5, -13, -109, 10, 65, 36, -67, 24, -87, 55, -78, -108, -43, -91, 50, 22, -29, 50, 63, 20, -77, 68, 24, -92, 64, -16, -83, 4, -59, 4, 26, 6, -71, 14, 62, -71, 94, 96, 102, 57, 89, -28, 38, 100, 37, -59, -47, 26, 102, 118, 92, 26, 67, 76, 121, 15, 117, 37, 81, 115, 88, -69, 50, 67, 65, 92, 104, 113, -12, 84, -53, 16, 49, 106, -53, 35, -78, -90, 16, 61, -56, -35, -99, -10, -19, -52, 15, -15, -43, 33, -30, -65, -57, 
  1, -44, -18, 16, 102, 0, -12, -50, 57, -66, -64, -6, 46, 72, -13, 58, -58, -27, 63, -15, -64, -38, 59, -21, 63, -12, 5, 98, -46, 95, 57, 19, 99, -41, -11, -35, 49, -69, -27, 10, 6, -3, 40, 92, 9, -61, 96, -81, 3, -28, 11, -18, -32, -69, -6, -78, 2, -4, 81, -52, -45, 101, -36, 28, -48, 66, 26, -16, 24, 117, -56, 3, -25, 108, 96, 74, -24, 48, -36, 29, 38, 107, -82, -17, 15, 86, 27, -40, 117, 0, 34, 118, 115, 38, 37, -25, 29, -8, 113, -18, 13, 14, 8, 10, 109, 92, 69, 117, 5, -37, 77, 47, 91, -73, -71, 54, -9, 108, -40, -68, 70, 6, -42, 7, 110, 34, 4, -73, 
  -19, 52, 93, 78, 87, -15, -21, 102, 57, 7, -18, 107, -21, 82, -64, -15, -57, 43, 108, -34, 69, -27, -59, 115, -34, -59, -36, 52, 12, -43, 1, -60, 9, 39, 24, 121, 115, -32, 88, -65, -78, -10, 108, -12, 50, -45, 30, 118, -54, 71, -24, -34, 115, 77, 51, -53, 97, -65, -1, -26, 51, -56, 67, 115, -2, 73, 7, 20, 39, -13, 66, -37, 49, 91, 36, 16, -85, -68, 63, -71, -75, -82, -85, 30, 43, 83, -53, 12, 7, 24, -15, 87, -98, -59, 65, 43, 37, -21, 86, -104, 81, 25, -9, -71, -57, -92, -64, 105, 40, -84, -79, -32, 89, 21, -50, 43, 85, 117, -33, 3, -48, 104, 45, 109, 25, 65, 69, 106, 
  -85, -36, 40, -111, 37, -4, -78, -22, -16, -37, -103, -54, -99, -84, -85, -61, -4, -70, -71, 29, -64, 69, -67, 64, -56, -96, -18, -40, -104, -81, 42, -50, -76, -103, 85, 70, 14, -81, -92, -47, -85, 9, -69, 44, -10, -27, 89, 14, -93, -108, -9, -95, 47, -68, 50, -87, -76, -70, -41, 61, -44, -62, -76, 66, 38, -67, 73, -94, -6, 80, 52, 45, 68, -55, -106, 23, 77, 7, -40, 25, 23, 32, 83, -2, 44, 13, 71, -3, -20, -92, -108, 76, 57, -44, -86, -86, 42, 10, 83, -71, -108, 87, 8, -4, -63, -8, -63, -89, -8, 44, -79, 0, -110, -66, -70, -85, 31, 26, -103, -101, 73, -67, -37, 2, 15, 85, -36, -54, 
  -3, 98, 20, -35, 1, -7, 57, 15, 100, 99, -51, 109, 101, 28, 30, -18, 16, -60, -30, 58, -10, -64, 107, -51, 23, 34, -32, -12, 67, 110, -41, 37, 115, -31, 36, 64, -60, 54, 35, 17, -33, -35, 57, 88, 29, -53, -66, 57, 14, 28, 50, 64, -60, 51, 70, -27, 83, -54, -37, 113, -47, 98, -44, 67, -46, 16, 13, -38, -44, -30, -69, 93, 3, 20, 7, 48, -50, -66, -57, -17, 94, 19, 26, -53, 4, 61, 89, 6, 55, 33, -57, 52, -32, 14, 63, -49, -36, -45, 116, -35, -12, 86, 69, -76, -16, 79, -73, -48, 18, 91, 127, 98, -63, -37, 73, 41, 21, -29, -24, 22, 127, 45, 73, -22, 60, 98, -59, 30, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,128 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0019884859211742878, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0092532755807042122, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.018088541924953461, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,2 } };
const TfArray<1, float> quant9_scale = { 1, { 0.022610126063227654, } };
const TfArray<1, int> quant9_zero = { 1, { 16 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2560, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 128), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1053054_9_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1053054_9_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1053054_9_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1053054_9_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1053054_9_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
